certificates migrations
ZbayApp/ZbayLite pull request #326
Opened 2021-07-27 12:20 UTC by Dinek007

2021-07-27 12:41 UTC, kowalski commented on src/renderer/store/selectors/contacts.ts
> +    if (accumulator) {
this is always at least `{}` so truthy

this whole `if-else` is redundant

2021-07-27 12:41 UTC, kowalski commented on src/renderer/store/certificates/certificates.saga.ts
> +    dmPublicKey: hexStringToArrayBuffer(dmPublicKey)
`hexStringToArrayBuffer` should be used inside `@zbay/identity`, here we should pass hex string

2021-07-27 12:43 UTC, kowalski requested changes
see inline comments

2021-07-29 14:01 UTC, kowalski commented on src/renderer/store/certificates/certificates.saga.ts
> +  console.log(user)
console.log

2021-07-29 14:42 UTC, kowalski approved these changes

2021-07-29 15:01 UTC, merged

2021-07-30 14:32 UTC, holmesworcester commented on src/renderer/sagas/socket/socket.saga.ts
> +  if (hasCertyficate) {
Confusing spelling: "Certyficate"