fix and improve messages grouping
ZbayApp/ZbayLite pull request #357
Opened 2021-08-09 16:14 UTC by Dinek007

2021-08-09 19:32 UTC, holmesworcester commented
@Dinek007 this should have tests to catch basic issues as well as the bug we're fixing now (messages from different users get grouped).

2021-08-19 10:46 UTC, kowalski requested changes

2021-08-19 10:46 UTC, kowalski commented on src/renderer/components/widgets/channels/ChannelMessage.js
> +  for (const el of parsedMessage) {
we shouldn't do this logic in render;

imo move this to the effect that is calling setParsedMessage

2021-08-20 16:09 UTC, kowalski approved these changes

2021-11-15 12:17 UTC, siepra approved these changes

2021-11-15 14:37 UTC, holmesworcester approved these changes

2021-11-15 14:37 UTC, holmesworcester commented on src/renderer/components/widgets/channels/ChannelMessage.tsx
> +            if (item !== ' ') {
In what case is item == ' ' ?

2021-11-15 14:37 UTC, holmesworcester commented on src/renderer/store/selectors/channel.ts
> +    lastCteatedAt = msg.createdAt
Does this approach allow us to style grouped messages differently than, say, a single message with a bunch of line breaks in it? 

Will it let us put controls on individual messages, say, if you wanted to delete a single message within a series of grouped messages?

2021-11-15 15:30 UTC, merged